version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "3001:3000"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=example
#       - DB_NAME=crypto_tracker
