version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - crypto-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - crypto-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_DB=crypto
      - DATABASE_POOL_MAX=5
      - DATABASE_POOL_MIN=1
      - DATABASE_POOL_ACQUIRE=30000
      - DATABASE_POOL_IDLE=10000
      - DATABASE_LOG=true
      - JWT_SECERT=JWT_SECERT
    depends_on:
      - postgres
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
